#!/bin/bash
git init -qqq
git remote add origin https://github.com/bid-d/docker-magento
git fetch origin -qqq
git checkout origin/omnyfy -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init
