#!/bin/bash
git init -qqq
git remote add origin https://github.com/bid-d/mageno-qarbi
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init
